var files_dup =
[
    [ "dvicmd.h", "dvicmd_8h.html", "dvicmd_8h" ],
    [ "dviout.c", "dviout_8c.html", "dviout_8c" ],
    [ "dviout.h", "dviout_8h.html", "dviout_8h" ],
    [ "fonts.c", "fonts_8c.html", "fonts_8c" ],
    [ "fonts.h", "fonts_8h.html", "fonts_8h" ],
    [ "funcs.c", "funcs_8c.html", "funcs_8c" ],
    [ "funcs.h", "funcs_8h.html", "funcs_8h" ],
    [ "global.h", "global_8h.html", "global_8h" ],
    [ "global_const.h", "global__const_8h.html", "global__const_8h" ],
    [ "inipool.c", "inipool_8c.html", "inipool_8c" ],
    [ "inputln.c", "inputln_8c.html", "inputln_8c" ],
    [ "inputln.h", "inputln_8h.html", "inputln_8h" ],
    [ "macros.h", "macros_8h.html", "macros_8h" ],
    [ "pool_str.c", "pool__str_8c.html", "pool__str_8c" ],
    [ "printout.c", "printout_8c.html", "printout_8c" ],
    [ "printout.h", "printout_8h.html", "printout_8h" ],
    [ "pure_func.c", "pure__func_8c.html", "pure__func_8c" ],
    [ "pure_func.h", "pure__func_8h.html", "pure__func_8h" ],
    [ "str.c", "str_8c.html", "str_8c" ],
    [ "str.h", "str_8h.html", "str_8h" ],
    [ "tex.c", "tex_8c.html", "tex_8c" ],
    [ "tex.h", "tex_8h.html", "tex_8h" ],
    [ "tex_constant.h", "tex__constant_8h.html", "tex__constant_8h" ],
    [ "tex_header.h", "tex__header_8h.html", "tex__header_8h" ],
    [ "tex_inc.h", "tex__inc_8h.html", "tex__inc_8h" ],
    [ "tex_types.h", "tex__types_8h.html", "tex__types_8h" ],
    [ "texfunc.h", "texfunc_8h.html", "texfunc_8h" ],
    [ "texmac.h", "texmac_8h.html", "texmac_8h" ],
    [ "texmath.c", "texmath_8c.html", "texmath_8c" ],
    [ "texmath.h", "texmath_8h.html", "texmath_8h" ]
];