name: C Build Status

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run test
      run: make test

  upload-codecov:
    # needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: gen report
      env:
        CFLAGS: "-g -O0 -I. -std=c11 -pedantic -Wall -Wno-unused-result --coverage -ftest-coverage -fprofile-arcs"
      run: make codecov
    - name: upload report
      run: bash <(curl -s https://codecov.io/bash)
